services:
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  api:
    build: ./server
    container_name: markitdown-server
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - UPLOAD_DIR=/data/uploads
      - OUTPUT_DIR=/data/output
      - TASK_STORE_FILE=/data/tasks.json
    volumes:
      - ./data:/data
    depends_on:
      - redis
    restart: always

  worker:
    build: ./worker
    container_name: markitdown-worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OUTPUT_DIR=/data/output
    volumes:
      - ./data:/data
    depends_on:
      - redis
    restart: always

  # Optionnal
  flower:
    image: mher/flower
    container_name: flower
    working_dir: /data
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - worker
      - redis